name: Check Markdown Links

on:
  schedule:
    # Run at 12:00 UTC on the 1st day of every 3rd month
    - cron: '0 12 1 */3 *'
  workflow_dispatch: # Allows manual execution

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run Links
        run: npm run links
