name: Check Markdown Links

on:
  schedule:
    # Run on Mondays at 9:00 UTC, every 2 weeks
    - cron: '0 9 */14 * *'
  workflow_dispatch: # Allows manual execution

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  link-check:
    name: Check Markdown Links
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - run: npm ci
      - name: Check Markdown Links
        run: npm run links
        continue-on-error: true
