name: Check Markdown Links

on:
  schedule:
    # Run on Mondays at 9:00 UTC, every 2 weeks
    - cron: '0 9 */14 * *'
  workflow_dispatch: # Allows manual execution

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: tcort/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: 'config.json'
